theme
{
  name = "modern"
  view = view.medium
  dark = true
  border.enabled = false
  border.size = 5
  border.color = default
  border.opacity = 29
  border.radius = 3
  image.enabled = true
  image.color = [#ffffff, #ffffff ]
  background.color = #000000
  background.opacity = 100
  background.effect = 0
  item.opacity = 0
  item.radius = 3
  item.text.normal = default
  item.text.select = default
  item.text.normal.disabled = default
  item.text.select.disabled = #999999
  item.back.select = default
  item.back.select.disabled = #000000
  item.border.normal = default
  item.border.normal.disabled = #000000
  item.border.select = default
  item.border.select.disabled = #000000
  font.size = auto
  font.name = "Segoe UI Variable Text"
  font.weight = false
  font.italic = false
  shadow.enabled = false
  shadow.size = 0
  shadow.opacity = 0
  shadow.color = #fff
  separator.size = 0
  separator.color = #fff
  separator.opacity = 0
  symbol.normal = #ffffff
  symbol.select = #ffffff
  symbol.normal.disabled = #ffffff
  symbol.select.disabled = #ffffff
  item.back.normal = #000000
  item.back.normal.disabled = #000000
}
