theme
{
  name = "modern"
  view = view.medium
  dark = true
  border.enabled = true
  border.size = 5
  border.color = #001220
  border.opacity = 29
  border.radius = 3
  image.enabled = true
  image.color = [#254751, #4c8fa5 ]
  background.color = #010409
  background.opacity = 100
  background.effect = 0
  item.opacity = 0
  item.radius = 3
  item.text.normal = #7ebfcc
  item.text.select = #9defff
  item.text.normal.disabled = #3b5460
  item.text.select.disabled = #4c747e
  item.back.select = #010409
  item.back.select.disabled = #010409
  item.border.normal = default
  item.border.normal.disabled = #010409
  item.border.select = #8ecae6
  item.border.select.disabled = #010409
  font.size = auto
  font.name = "Segoe UI Variable Text"
  font.weight = true
  font.italic = false
  shadow.enabled = false
  shadow.size = 1
  shadow.opacity = 20
  shadow.color = #8ecae6
  separator.size = 0
  separator.color = #fff
  separator.opacity = 0
  symbol.normal = #4c8fa5
  symbol.select = #ffffff
  symbol.normal.disabled = #ffffff
  symbol.select.disabled = #ffffff
  item.back.normal = #010409
  item.back.normal.disabled = #010409
}
