theme
{
  name = "modern"
  view = view.medium
  dark = true
  border.enabled = false
  border.size = 5
  border.color = default
  border.opacity = 29
  border.radius = 3
  image.enabled = true
  image.effect = 1
  image.color = [#00acc1, #5e81ac]
  symbol.effect = 1
  symbol.normal = [#00acc1, #ffffff]
  background.color = #00acc1
  background.opacity = 10
  background.effect = 3
  item.opacity = 0
  item.radius = 3
  item.text.normal = default
  item.text.select = default
  item.text.normal.disabled = default
  item.text.select.disabled = #ffffff
  item.back.select = default
  item.back.select.disabled = default
  item.border.normal = default
  item.border.normal.disabled = default
  item.border.select = default
  item.border.select.disabled = default
  font.size = auto
  font.name = "Segoe UI Variable Text"
  font.weight = false
  font.italic = false
  shadow.enabled = true
  shadow.size = 7
  shadow.opacity = 28
  shadow.color = #88c0d0
  separator.size = 0
  separator.color = #fff
  separator.opacity = 0
  symbol.select = #ffffff
  symbol.normal.disabled = #ffffff
  symbol.select.disabled = #ffffff
  item.back.normal = default
  item.back.normal.disabled = default
  border.padding.top = 5
  border.padding.bottom = 5
  border.padding.left = 0
  border.padding.right = 0
}
