theme
{
  name = "modern"
  view = view.medium
  border.enabled = true
  border.size = 5
  border.color = #d8dee9
  border.opacity = 29
  border.radius = 3
  image.enabled = true
  image.color = [#ffffff, #ffffff ]
  background.color = default
  background.image = 'D:/iMA/Pictures/wallpaper/cityscape_night.jpg'
  background.opacity = 38
  background.effect = 4
  item.opacity = 0
  item.radius = 3
  item.text.normal = default
  item.text.select = default
  item.text.normal.disabled = default
  item.text.select.disabled = #ffffff
  item.back.select = #02000d94
  item.back.select.disabled = default
  item.border.normal = default
  item.border.normal.disabled = default
  item.border.select = default
  item.border.select.disabled = default
  font.size = auto
  font.name = "Segoe UI Variable Text"
  font.weight = false
  font.italic = false
  shadow.enabled = false
  shadow.size = 0
  shadow.opacity = 0
  shadow.color = #fff
  separator.size = 0
  separator.color = #fff
  separator.opacity = 0
  symbol.normal = #ffffff
  symbol.select = #ffffff
  symbol.normal.disabled = #ffffff
  symbol.select.disabled = #ffffff
  dark = true
  item.back.normal = default
  item.back.normal.disabled = default
  border.padding.top = 5
  border.padding.bottom = 5
  border.padding.left = 0
  border.padding.right = 0
}
